import Head from '../node_modules/next/head';

export default function Home() {
    return (
        <div className="">
            <Head>
                <title>Reddit 2.0 Clone</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </div>
    );
}
